# Generated by Django 4.2.4 on 2023-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_addition',
            field=models.ImageField(default='', upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(default='', upload_to='products_images'),
        ),
    ]
